# Generated by Django 3.1.2 on 2021-10-11 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_auto_20210922_0616'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time this object was created.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date and time this object was last modified.')),
                ('activity_type', models.CharField(choices=[('reminder', 'Reminder'), ('account_activation', 'Account Activation'), ('reset_password', 'Reset Password'), ('change_password', 'Change Password')], max_length=32)),
                ('org_user_filter', models.CharField(blank=True, max_length=100, null=True)),
                ('user_msg', models.TextField(blank=True, null=True)),
                ('questionnaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questionnaire')),
                ('to_users', models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
