# Generated by Django 3.1.2 on 2021-09-03 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time this object was created.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date and time this object was last modified.')),
                ('name', models.CharField(max_length=255)),
                ('configuration', models.JSONField(blank=True, default=dict, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('close', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time this object was created.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date and time this object was last modified.')),
                ('label', models.CharField(max_length=1024)),
                ('order', models.PositiveIntegerField(default=0)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questionnaire')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time this object was created.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date and time this object was last modified.')),
                ('instruction', models.TextField(max_length=1024, null=True)),
                ('input_type', models.CharField(choices=[('dropdown', 'Dropdown'), ('text', 'Text'), ('checkbox', 'Checkbox'), ('boolean', 'Boolean'), ('date', 'Date'), ('integer', 'Integer')], db_index=True, max_length=32)),
                ('name', models.CharField(blank=True, db_index=True, max_length=512, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('options', models.JSONField(blank=True, default=dict, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.question')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.section')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
