# Generated by Django 3.1.2 on 2021-09-20 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time this object was created.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date and time this object was last modified.')),
                ('instruction', models.TextField(blank=True, max_length=1024, null=True)),
                ('input_type', models.CharField(choices=[('dropdown', 'Dropdown'), ('shorttext', 'Shorttext'), ('longtext', 'Longtext'), ('checkbox', 'Checkbox'), ('radio', 'Radio'), ('number', 'Number')], db_index=True, max_length=32)),
                ('name', models.CharField(blank=True, db_index=True, max_length=512, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('options', models.JSONField(blank=True, default=dict, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time this object was created.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date and time this object was last modified.')),
                ('name', models.CharField(max_length=255)),
                ('configuration', models.JSONField(blank=True, default=dict, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('close', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time this object was created.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date and time this object was last modified.')),
                ('label', models.CharField(max_length=1024)),
                ('order', models.PositiveIntegerField(default=0)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questionnaire')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionLogic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time this object was created.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date and time this object was last modified.')),
                ('action', models.CharField(choices=[('make_required', 'Make Required'), ('show', 'Show'), ('hide', 'Hide')], max_length=32)),
                ('when', models.CharField(choices=[('answered', 'target is answered'), ('parent', 'parent is answered'), ('parent_value', 'parent response is equal to'), ('target_value', 'target response is equal to')], max_length=32)),
                ('values', models.CharField(blank=True, max_length=255, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.question')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='questionnaire.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.section'),
        ),
    ]
