# Generated by Django 3.1.2 on 2021-09-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionlogic',
            name='target',
        ),
        migrations.AlterField(
            model_name='questionlogic',
            name='action',
            field=models.CharField(choices=[('make_required', 'Make Required')], max_length=32),
        ),
        migrations.AlterField(
            model_name='questionlogic',
            name='when',
            field=models.CharField(choices=[('parent', 'parent is answered'), ('parent_value', 'parent response is equal to')], max_length=32),
        ),
    ]
