# Generated by Django 3.1.2 on 2021-09-11 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20210903_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_mandatory',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='QuestionLogic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time this object was created.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date and time this object was last modified.')),
                ('action', models.CharField(choices=[('make_required', 'Make Required'), ('show', 'Show'), ('hide', 'Hide')], max_length=32)),
                ('when', models.CharField(choices=[('answered', 'target is answered'), ('parent', 'parent is answered'), ('parent_value', 'parent response is equal to'), ('target_value', 'target response is equal to')], max_length=32)),
                ('values', models.JSONField(blank=True, default=dict, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.question')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='questionnaire.question')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
