# Generated by Django 3.1.2 on 2021-09-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20210922_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_mandatory',
            field=models.BooleanField(default=False),
        ),
    ]
