# Generated by Django 3.1.2 on 2021-09-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_auto_20210911_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionlogic',
            name='values',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
