# Generated by Django 3.1.2 on 2021-10-25 11:57

from django.db import migrations


def update_number_question(apps, schema_editor):
    Question = apps.get_model("questionnaire", "Question")

    for question in Question.objects.filter(input_type="number"):
        options = question.options
        if "validations" in options:
            validations = options["validations"]
        else:
            validations = {}

        if "min" not in validations:
            validations["min"] = 0

        options["validations"] = validations
        question.options = options
        question.save()


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_auto_20210922_0616'),
    ]

    operations = [
        migrations.RunPython(update_number_question)
    ]
