# Generated by Django 3.1.2 on 2021-09-20 09:26

from django.db import migrations
from django.contrib.auth.management import create_permissions

def create_staff_groups(apps, schema_editor):
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, verbosity=0)
        app_config.models_module = None

    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    # Create groups
    admin = Group.objects.create(name="Admin")
    super_admin = Group.objects.create(name="SuperAdmin")

    admin_perm_models = {
        "authentication": {
            "user": ["add", "view", "change", "delete"]
        },
        "questionnaire": {
            "questionnaire": ["view", "change"],
            "question": ["view"],
            "section": ["view"],
            "questionlogic": ["view"]
        },
        "response": {
            "response": ["view"],
            "questionresponse": ["view"]
        }

    }

    super_admin_perm_models = {
        "authentication": {
            "user": ["add", "view", "change", "delete"]
        },
        "questionnaire": {
            "questionnaire": ["add", "view", "change", "delete"],
            "question": ["add", "view", "change", "delete"],
            "section": ["add", "view", "change", "delete"],
            "questionlogic": ["add", "view", "change", "delete"]
        },
        "organisation": {
            "organisation": ["add", "view", "change", "delete"],
            "group": ["add", "view", "change", "delete"],
        },
        "response": {
            "response": ["view"],
            "questionresponse": ["view"]
        }
    }

    # Assign perms to groups
    for app_label, models in admin_perm_models.items():
        for model, perms in models.items():
            for perm in perms:
                permission = Permission.objects.filter(
                    content_type__app_label=app_label, codename=f"{perm}_{model}"
                ).first()
                admin.permissions.add(permission.id)


    for app_label, models in super_admin_perm_models.items():
        for model, perms in models.items():
            for perm in perms:
                permission = Permission.objects.filter(
                    content_type__app_label=app_label, codename=f"{perm}_{model}"
                ).first()
                super_admin.permissions.add(permission.id)


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '__latest__'),
        ('auth', '__latest__'),
        ('sessions', '__latest__'),
        ('organisation', '0001_initial'),
        ('questionnaire', '0001_initial'),
        ('response', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_staff_groups)
    ]
