# Generated by Django 3.1.2 on 2021-09-17 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('authentication', '0004_auto_20210917_0550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time this object was created.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date and time this object was last modified.')),
                ('target_object_id', models.PositiveIntegerField()),
                ('sharer_object_id', models.PositiveIntegerField()),
                ('relationship', models.CharField(choices=[('creator', 'Creator'), ('admin', 'Admin'), ('viewer', 'Viewer')], max_length=32)),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sharer_content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'authentication'), ('model', 'user')), models.Q(('app_label', 'organisation'), ('model', 'organisation')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='authentication_sharer_share_related', to='contenttypes.contenttype')),
                ('target_content_type', models.ForeignKey(limit_choices_to=models.Q(('app_label', 'questionnaire'), ('model', 'questionnaire')), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
