# Generated by Django 3.1.2 on 2021-09-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresponse',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
